DROP TABLE IF EXISTS CHAMADO;

CREATE TABLE IF NOT EXISTS CHAMADO(
	Id INT AUTO_INCREMENT NOT NULL,
    LoginId INT NOT NULL,
    SetorId INT NOT NULL,
	Problema VARCHAR(200) NOT NULL,
    PathArquivos VARCHAR(200),
    MomentoAberto DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (LoginId)
        REFERENCES Login (Id),
	FOREIGN KEY (SetorId)
        REFERENCES Setor (Id)
);